name: Building Blocks

on:
 push:
 workflow_dispatch:

jobs:
  echo-hello:
   runs-on: ubuntu-latest
   steps:
    - run: echo "Say Hello"
  echo-goodbye:
   runs-on: ubuntu-latest
   steps:
    - run: echo "Failed step"
    - run: echo "Say goodbye"
   
