name: Using Actions

on:
 push
jobs:
  echo_java_mavenrepo:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-java@v4
       with:
        java-version: '17'
        distribution: 'temurin'
     - name: Setup Maven Action
       uses: s4u/setup-maven-action@< version >

     - run: mvn -V ...
       
     
