name: 2.Event Filters and Activity Types

on: 
 pull_request:
  types:
   - closed
  branches:
    - master

jobs:
 echo_filter_activity:
   runs-on: ubuntu-latest
   steps:
     - run: echo "Running whenever a PR is closed"
